version: '3.9'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: django-grocery
    container_name: grocery-container_name
    ports:
      - "8000:3000"
    volumes:
      - ./:/django
    command: python manage.py runserver 0.0.0.0:3000

