version: '3.9'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: sakib059/django-grocery:latest
    container_name: grocery-container
    ports:
      - "8000:3000"
    volumes:
      - ./:/django
    command: >
      sh -c "gunicorn groceryRecommendation.wsgi:application --bind 0.0.0.0:${PORT:-3000}"

