name: Image push and deploy
on:
    push:
        branches:
            - master
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
           - name: Get code
             uses: actions/checkout@v4       
           - name: Set up docker Buildx
             uses: docker/setup-buildx-action@v3 
    push:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: Dockerhub login
              uses: docker/login-action@v3
              with:
                 username: ${{secrets.USERNAME}}
                 password: ${{secrets.TOKEN}} 
            - name: build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: sakib059/django-grocery:latest           
    deploy:
        needs: push
        runs-on: ubuntu-latest
        steps:
            - name: Deployment
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                service-id: ${{ secrets.RENDER_SERVICE_ID }}
                api-key: ${{ secrets.RENDER_SERVICE_ID }}

    