name: Image push and deploy
on:
    push:
        branches:
            - master
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Set up Python environment
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'    
            - name: Check Docker and Docker Compose versions
              run: |
                      docker --version
                      docker compose version        
            - name: Set up docker Buildx
              uses: docker/setup-buildx-action@v3 
            - name: Dockerhub login
              uses: docker/login-action@v3
              with:
                 username: ${{secrets.USERNAME}}
                 password: ${{secrets.TOKEN}} 
            - name: Build and tag using Docker Compose
              run: |
                     docker compose -f docker-compose.yaml build
                     docker tag sakib059/django-grocery:latest sakib059/django-grocery:${{ github.sha }}
                     docker compose -f docker-compose.yaml push
                     docker push sakib059/django-grocery:${{ github.sha }}
            - name: View all the images
              run: docker images                    
    deploy:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: Deployment
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                service-id: ${{ secrets.RENDER_SERVICE_ID }}
                api-key: ${{ secrets.RENDER_API_KEY }}

    