name: Image push and deploy
on:
    push:
        branches:
            - master
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Set up Python environment
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'    
            - name: Check Docker and Docker Compose versions
              run: |
                      docker --version
                      docker compose version        
            - name: Set up docker Buildx
              uses: docker/setup-buildx-action@v3 
            - name: Dockerhub login
              uses: docker/login-action@v3
              with:
                 username: ${{secrets.USERNAME}}
                 password: ${{secrets.TOKEN}} 
            - name: build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: sakib059/django-grocery:latest           
    # deploy:
    #     needs: setup
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Deployment
    #           uses: johnbeynon/render-deploy-action@v0.0.8
    #           with:
    #             service-id: ${{ secrets.RENDER_SERVICE_ID }}
    #             api-key: ${{ secrets.RENDER_API_KEY }}

    