name: Image push and deploy
on:
    pull_request
    # push:
    #     branches:
    #         - master
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Set up Python environment
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Running the unit tests
              run: python manage.py test
            - name: Lint testing using flake8
              run: flake8 .            
            # - name: Check Docker and Docker Compose versions
            #   run: |
            #           docker --version
            #           docker compose version        
            - name: Set up docker Buildx
              uses: docker/setup-buildx-action@v3 
            - name: Dockerhub login
              uses: docker/login-action@v3
              with:
                 username: ${{secrets.USERNAME}}
                 password: ${{secrets.TOKEN}} 
            - name: Build and push
              run: |
                docker build -t sakib059/django-grocery:latest .
                docker tag sakib059/django-grocery:latest sakib059/django-grocery:latest
                docker push sakib059/django-grocery:latest
            - name: View all the images
              run: docker images                    
    deploy:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: Deployment
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                service-id: ${{ secrets.RENDER_SERVICE_ID }}
                api-key: ${{ secrets.RENDER_API_KEY }}

    